SET IDENTITY_INSERT [dbo].[Patients] ON
INSERT INTO [dbo].[Patients] ([PatientId], [Name], [Gender], [ExpectedTreatmentTime], [Diagnosis], [Physician], [RecentWeight], [MedicalHistory], [MedicationInstructions], [Operator], [OperationTime], [Number]) VALUES (1, N'陳先生', N'Male', N'111', N'肺癌', N'ahh', 60, N'a', N'10:30', N'張', N'2024-04-23 00:00:00', 11)
INSERT INTO [dbo].[Patients] ([PatientId], [Name], [Gender], [ExpectedTreatmentTime], [Diagnosis], [Physician], [RecentWeight], [MedicalHistory], [MedicationInstructions], [Operator], [OperationTime], [Number]) VALUES (2, N'林小姐', N'Female', N'11', N'結腸直腸癌', N'c', 0, N'ccc', N'6:0', N'0', N'0001-01-01 00:00:00', 11)
INSERT INTO [dbo].[Patients] ([PatientId], [Name], [Gender], [ExpectedTreatmentTime], [Diagnosis], [Physician], [RecentWeight], [MedicalHistory], [MedicationInstructions], [Operator], [OperationTime], [Number]) VALUES (3, N'王', N'Male', N'111', N'肺癌', N'f', 0, N'f', N'1:30', NULL, N'0001-01-01 00:00:00', 11)
INSERT INTO [dbo].[Patients] ([PatientId], [Name], [Gender], [ExpectedTreatmentTime], [Diagnosis], [Physician], [RecentWeight], [MedicalHistory], [MedicationInstructions], [Operator], [OperationTime], [Number]) VALUES (4, N'黃', N'Female', N'11', N'其他癌', N'', 0, N'', N'', NULL, N'2024-04-23 13:24:20', 11)
INSERT INTO [dbo].[Patients] ([PatientId], [Name], [Gender], [ExpectedTreatmentTime], [Diagnosis], [Physician], [RecentWeight], [MedicalHistory], [MedicationInstructions], [Operator], [OperationTime], [Number]) VALUES (5, N'張', N'Male', N'11', N'其他癌', N'', 0, N'', N'', NULL, N'2024-04-23 14:20:44', 11)
INSERT INTO [dbo].[Patients] ([PatientId], [Name], [Gender], [ExpectedTreatmentTime], [Diagnosis], [Physician], [RecentWeight], [MedicalHistory], [MedicationInstructions], [Operator], [OperationTime], [Number]) VALUES (7, N'蕭', N'Male', N'11', N'肺癌', N'', 0, N'', N'', NULL, N'0001-01-01 00:00:00', 11)
INSERT INTO [dbo].[Patients] ([PatientId], [Name], [Gender], [ExpectedTreatmentTime], [Diagnosis], [Physician], [RecentWeight], [MedicalHistory], [MedicationInstructions], [Operator], [OperationTime], [Number]) VALUES (8, N'林', N'Male', N'1', N'結直腸癌', N'', 0, N'', N'6:0', NULL, N'0001-01-01 00:00:00', 11)
SET IDENTITY_INSERT [dbo].[Patients] OFF
DELETE FROM dbo.Patients WHERE PatientId IS NULL;